### ISSUE TITLE
java.lang.IncompatibleClassChangeError on jenkins for ontrack build creation

### ISSUE THREAD

**Issue by flesire** [nemerosa/ontrack-jenkins#30]
ERROR: Publisher net.nemerosa.ontrack.jenkins.OntrackBuildNotifier aborted due to exception
java.lang.IncompatibleClassChangeError: the number of constructors during runtime and compile time for java.lang.RuntimeException do not match. Expected -1 but got 5

Jenkins 1.597 runs on JDK1.8.0_31 with ontrack plugin 2.3-SNAPSHOT
Ontrack version is 2.3.2

**Comment by dcoraboeuf** [comment]
Have you tried version 2.2 of the plug-in?

**Comment by flesire** [comment]
Same problem with 2.2.0

**Comment by dcoraboeuf** [comment]
I think this is a Groovy problem: conflict of version between the Jenkins version and the one the DSL was compiled against.

There must be an initial problem (look at your logs) and then, the DSL module tries to create a `DSLException` but cannot because of the Groovy problem. I'll try to make the `DSLException` a standard Java class instead of a Groovy one.

**Comment by dcoraboeuf** [comment]
Fixed in 2.2.1
